import type { Tool, ToolCategory, Template } from "@shared/schema";
import {
  FileText,
  Image,
  Type,
  Sparkles,
  ArrowRightLeft,
  Calculator,
  FileImage,
  FilePlus2,
  Scissors,
  Minimize2,
  RotateCw,
  Lock,
  Unlock,
  ImageDown,
  Crop,
  Palette,
  Wand2,
  CaseSensitive,
  ListX,
  Lightbulb,
  CheckCircle2,
  QrCode,
  Barcode,
  Key,
  UserPlus,
  FileCode,
  Eye,
  Percent,
  Wallet,
  GraduationCap,
  DollarSign,
} from "lucide-react";

export const toolCategories: ToolCategory[] = [
  {
    id: "pdf",
    name: "PDF Tools",
    description: "Convert, merge, split, compress, and edit PDF files",
    icon: "FileText",
    toolCount: 6,
    path: "/tools/pdf",
  },
  {
    id: "image",
    name: "Image Tools",
    description: "Compress, resize, crop, and convert images",
    icon: "Image",
    toolCount: 4,
    path: "/tools/image",
  },
  {
    id: "text",
    name: "Text Tools",
    description: "Process and manipulate text content",
    icon: "Type",
    toolCount: 4,
    path: "/tools/text",
  },
  {
    id: "generators",
    name: "Generators",
    description: "Generate QR codes, barcodes, passwords, and more",
    icon: "Sparkles",
    toolCount: 4,
    path: "/tools/generators",
  },
  {
    id: "converters",
    name: "Converters",
    description: "Convert between different formats",
    icon: "ArrowRightLeft",
    toolCount: 2,
    path: "/tools/converters",
  },
  {
    id: "calculators",
    name: "Calculators",
    description: "Financial and academic calculators",
    icon: "Calculator",
    toolCount: 4,
    path: "/tools/calculators",
  },
];

export const allTools: Tool[] = [
  // PDF Tools
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages to high-quality JPG images",
    category: "pdf",
    path: "/tool/pdf-to-jpg",
    icon: "FileImage",
    isPro: false,
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG images to PDF documents",
    category: "pdf",
    path: "/tool/jpg-to-pdf",
    icon: "FilePlus2",
    isPro: false,
  },
  {
    id: "pdf-merge",
    name: "PDF Merge",
    description: "Combine multiple PDF files into one",
    category: "pdf",
    path: "/tool/pdf-merge",
    icon: "FilePlus2",
    isPro: false,
  },
  {
    id: "pdf-split",
    name: "PDF Split",
    description: "Split PDF into separate pages or ranges",
    category: "pdf",
    path: "/tool/pdf-split",
    icon: "Scissors",
    isPro: false,
  },
  {
    id: "pdf-compress",
    name: "PDF Compress",
    description: "Reduce PDF file size without losing quality",
    category: "pdf",
    path: "/tool/pdf-compress",
    icon: "Minimize2",
    isPro: false,
  },
  {
    id: "pdf-rotate",
    name: "PDF Rotate",
    description: "Rotate PDF pages to any angle",
    category: "pdf",
    path: "/tool/pdf-rotate",
    icon: "RotateCw",
    isPro: false,
  },

  // Image Tools
  {
    id: "image-compress",
    name: "Image Compressor",
    description: "Compress images to reduce file size",
    category: "image",
    path: "/tool/image-compress",
    icon: "Minimize2",
    isPro: false,
  },
  {
    id: "image-resize",
    name: "Image Resizer",
    description: "Resize images to custom dimensions",
    category: "image",
    path: "/tool/image-resize",
    icon: "ImageDown",
    isPro: false,
  },
  {
    id: "image-crop",
    name: "Image Cropper",
    description: "Crop images to desired area",
    category: "image",
    path: "/tool/image-crop",
    icon: "Crop",
    isPro: false,
  },
  {
    id: "image-converter",
    name: "Image Format Converter",
    description: "Convert images between formats (PNG, JPG, WebP)",
    category: "image",
    path: "/tool/image-converter",
    icon: "ArrowRightLeft",
    isPro: false,
  },

  // Text Tools
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, and sentences",
    category: "text",
    path: "/tool/word-counter",
    icon: "Type",
    isPro: false,
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text to uppercase, lowercase, or title case",
    category: "text",
    path: "/tool/case-converter",
    icon: "CaseSensitive",
    isPro: false,
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for design mockups",
    category: "text",
    path: "/tool/lorem-ipsum",
    icon: "Lightbulb",
    isPro: false,
  },
  {
    id: "grammar-checker",
    name: "Grammar Checker",
    description: "Check grammar and spelling in your text",
    category: "text",
    path: "/tool/grammar-checker",
    icon: "CheckCircle2",
    isPro: false,
  },

  // Generators
  {
    id: "qr-code",
    name: "QR Code Generator",
    description: "Create QR codes for URLs, text, or contacts",
    category: "generators",
    path: "/tool/qr-code",
    icon: "QrCode",
    isPro: false,
  },
  {
    id: "barcode",
    name: "Barcode Generator",
    description: "Generate barcodes in multiple formats",
    category: "generators",
    path: "/tool/barcode",
    icon: "Barcode",
    isPro: false,
  },
  {
    id: "password",
    name: "Password Generator",
    description: "Create secure random passwords",
    category: "generators",
    path: "/tool/password",
    icon: "Key",
    isPro: false,
  },
  {
    id: "username",
    name: "Username Generator",
    description: "Generate unique usernames",
    category: "generators",
    path: "/tool/username",
    icon: "UserPlus",
    isPro: false,
  },

  // Converters
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    description: "Convert HTML content to PDF",
    category: "converters",
    path: "/tool/html-to-pdf",
    icon: "FileCode",
    isPro: false,
  },
  {
    id: "image-to-text",
    name: "Image to Text (OCR)",
    description: "Extract text from images using OCR",
    category: "converters",
    path: "/tool/image-to-text",
    icon: "Eye",
    isPro: false,
  },

  // Calculators
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages and percentage change",
    category: "calculators",
    path: "/tool/percentage-calculator",
    icon: "Percent",
    isPro: false,
  },
  {
    id: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate loan payments and interest",
    category: "calculators",
    path: "/tool/loan-calculator",
    icon: "Wallet",
    isPro: false,
  },
  {
    id: "gpa-calculator",
    name: "GPA Calculator",
    description: "Calculate your Grade Point Average",
    category: "calculators",
    path: "/tool/gpa-calculator",
    icon: "GraduationCap",
    isPro: false,
  },
  {
    id: "zakat-calculator",
    name: "Zakat Calculator",
    description: "Calculate Islamic charity (Zakat) amount",
    category: "calculators",
    path: "/tool/zakat-calculator",
    icon: "DollarSign",
    isPro: false,
  },
];

export const templates: Template[] = [
  {
    id: "resume-modern",
    name: "Modern Resume",
    category: "resume",
    description: "Clean and professional resume template",
    thumbnailUrl: "/templates/resume-modern.png",
    downloadUrl: "/api/templates/download/resume-modern",
  },
  {
    id: "resume-creative",
    name: "Creative Resume",
    category: "resume",
    description: "Stand out with this creative design",
    thumbnailUrl: "/templates/resume-creative.png",
    downloadUrl: "/api/templates/download/resume-creative",
  },
  {
    id: "invoice-professional",
    name: "Professional Invoice",
    category: "invoice",
    description: "Business invoice template",
    thumbnailUrl: "/templates/invoice-professional.png",
    downloadUrl: "/api/templates/download/invoice-professional",
  },
  {
    id: "invoice-simple",
    name: "Simple Invoice",
    category: "invoice",
    description: "Minimalist invoice design",
    thumbnailUrl: "/templates/invoice-simple.png",
    downloadUrl: "/api/templates/download/invoice-simple",
  },
  {
    id: "salary-slip",
    name: "Salary Slip",
    category: "salary-slip",
    description: "Monthly salary slip template",
    thumbnailUrl: "/templates/salary-slip.png",
    downloadUrl: "/api/templates/download/salary-slip",
  },
  {
    id: "offer-letter",
    name: "Offer Letter",
    category: "offer-letter",
    description: "Job offer letter template",
    thumbnailUrl: "/templates/offer-letter.png",
    downloadUrl: "/api/templates/download/offer-letter",
  },
  {
    id: "leave-application",
    name: "Leave Application",
    category: "office-forms",
    description: "Employee leave request form",
    thumbnailUrl: "/templates/leave-application.png",
    downloadUrl: "/api/templates/download/leave-application",
  },
  {
    id: "meeting-minutes",
    name: "Meeting Minutes",
    category: "office-forms",
    description: "Meeting notes and action items",
    thumbnailUrl: "/templates/meeting-minutes.png",
    downloadUrl: "/api/templates/download/meeting-minutes",
  },
];

export function getToolsByCategory(categoryId: string): Tool[] {
  return allTools.filter((tool) => tool.category === categoryId);
}

export function getToolById(toolId: string): Tool | undefined {
  return allTools.find((tool) => tool.id === toolId);
}

export function getPopularTools(): Tool[] {
  return allTools.slice(0, 12);
}
